### PR TITLE
Solved Entire Navbar Problem

### PR DESCRIPTION
**Pull request by Gautam-Arora24**
Now I think the Navbar is working across whole application. Kindly check and let me know

### CODE REVIEW

**Comment by Aman-Codes** [comment]
Looks good to me.

**Comment by Gautam-Arora24** [comment]
Have you checked locally and was it working?

**Comment by Aman-Codes** [comment]
Yes I have checked it is working locally 🎉

**Comment by Gautam-Arora24** [comment]
Finally. Thanks, I loved working on this issue

**Pull request merged**
